/**
 * This file is part of lavagna.
 *
 * lavagna is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * lavagna is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with lavagna.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.lavagna.model;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import lombok.Getter;

@Getter
public class ImportContext {
	// map the ids from the imported file to the ids generated by the system
	private final Map<Integer, Integer> columns = new HashMap<>();
	private final Map<Integer, Integer> commentsId = new HashMap<>();
	private final Map<Integer, Integer> actionListId = new HashMap<>();
	private final Map<Integer, Integer> actionItemId = new HashMap<>();
	private final Map<Integer, Integer> fileId = new HashMap<>();
	//

	private final Set<String> importedProject = new HashSet<>();
	private final Set<String> importedBoard = new HashSet<>();

}