--
-- This file is part of lavagna.
--
-- lavagna is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- lavagna is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with lavagna.  If not, see <http://www.gnu.org/licenses/>.
--

CREATE TABLE LA_PROJECT_MAIL_TICKET (
	MAIL_TICKET_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	MAIL_TICKET_NAME VARCHAR(128) NOT NULL,
	MAIL_TICKET_PROJECT_ID_FK INTEGER NOT NULL,
	MAIL_TICKET_BOARD_ID_FK INTEGER NOT NULL,
	MAIL_TICKET_COLUMN_ID_FK INTEGER NOT NULL,
	MAIL_TICKET_LAST_CHECKED TIMESTAMP DEFAULT NULL,
	MAIL_TICKET_MAIL_CONFIG CLOB,
	MAIL_TICKET_METADATA CLOB
);
